=== thefringeninja/Transacto/src/Transacto/Messages/AccountDefined.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"type": "object",
	"title": "Account Defined",
	"additionalProperties": false,
	"required": [
		"accountNumber",
		"accountName",
		"cashFlowCategory"
	],
	"properties": {
		"accountNumber": {
			"title": "Account Number",
			"type": "integer"
		},
		"accountName": {
			"title": "Account Name",
			"type": "string",
			"maxLength": 256
		},
		"cashFlowCategory": {
			"$ref": "CashFlowCategoryType.schema.json"
		},
		"affectsCash" : {
			"title": "Affects Cash",
			"type": "boolean",
			"default": false
		}
	}
}

=== thefringeninja/Transacto/test/Transacto.IntegrationTests/Integration/ChartOfAccounts.json
[
	{
		"accountName": "Petty Cash",
		"accountNumber": 1000,
		"cashFlowCategory": "operations",
		"affectsCash": true
	},
	{
		"accountName": "Cash on Hand",
		"accountNumber": 1010,
		"cashFlowCategory": "operations",
		"affectsCash": true
	},
	{
		"accountName": "Regular Checking Account",
		"accountNumber": 1020,
		"cashFlowCategory": "operations",
		"affectsCash": true
	},
	{
		"accountName": "Payroll Checking Account",
		"accountNumber": 1030,
		"cashFlowCategory": "operations",
		"affectsCash": true
	},
	{
		"accountName": "Savings Account",
		"accountNumber": 1040,
		"cashFlowCategory": "operations",
		"affectsCash": true
	},
	{
		"accountName": "Special Account",
		"accountNumber": 1050,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Investments - Money Market",
		"accountNumber": 1060,
		"cashFlowCategory": "investment",
		"affectsCash": false
	},
	{
		"accountName": "Investments - Certificates of Deposit",
		"accountNumber": 1070,
		"cashFlowCategory": "investment",
		"affectsCash": false
	},
	{
		"accountName": "Accounts Receivable",
		"accountNumber": 1100,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Other Receivables",
		"accountNumber": 1140,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Allowance for Doubtful Accounts",
		"accountNumber": 1150,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Raw Materials Inventory",
		"accountNumber": 1200,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Supplies Inventory",
		"accountNumber": 1205,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Work in Progress Inventory",
		"accountNumber": 1210,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Finished Goods Inventory",
		"accountNumber": 1220,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Prepaid Expenses",
		"accountNumber": 1400,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Employee Advances",
		"accountNumber": 1410,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Notes Receivable - Current",
		"accountNumber": 1420,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Prepaid Interest",
		"accountNumber": 1430,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Other Current Assets",
		"accountNumber": 1470,
		"cashFlowCategory": "operations",
		"affectsCash": false
	},
	{
		"accountName": "Furniture and Fixtures",
		"accountNumber": 1500,
		"cashFlowCategory": "investment",
		"affectsCash": false
	},
	{
		"accountName": "Equipment",
		"accountNumber": 1510,
		"cashFlowCategory": "investment",
		"affectsCash": false
	},
	{
		"accountName": "Vehicles",
		"accountNumber": 1520,
		"cashFlowCategory": "investment",
		"affectsCash": false
	},
	{
		"accountName": "Other Depreciable Property",
		"accountNumber": 1530,
		"cashFlowCategory": "investment",
		"affectsCash": false
	},
	{
		"accountName": "Leasehold Improvements",
		"accountNumber": 1540,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Buildings",
		"accountNumber": 1550,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Building Improvements",
		"accountNumber": 1560,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Land",
		"accountNumber": 1690,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Furniture and Fixtures",
		"accountNumber": 1700,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Equipment",
		"accountNumber": 1710,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Vehicles",
		"accountNumber": 1720,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Other",
		"accountNumber": 1730,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Leasehold",
		"accountNumber": 1740,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Buildings",
		"accountNumber": 1750,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Depreciation, Building Improvements",
		"accountNumber": 1760,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Deposits",
		"accountNumber": 1900,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Organization Costs",
		"accountNumber": 1910,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accumulated Amortization, Organization Costs",
		"accountNumber": 1915,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Notes Receivable, Non-current",
		"accountNumber": 1920,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Other Non-current Assets",
		"accountNumber": 1990,
		"cashFlowCategory": "investment"
	},
	{
		"accountName": "Accounts Payable",
		"accountNumber": 2000,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Accrued Expenses",
		"accountNumber": 2300,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Sales Tax Payable",
		"accountNumber": 2310,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Wages Payable",
		"accountNumber": 2320,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "401-K Deductions Payable",
		"accountNumber": 2330,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Health Insurance Payable",
		"accountNumber": 2335,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Federal Payroll Taxes Payable",
		"accountNumber": 2340,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "FUTA Tax Payable",
		"accountNumber": 2350,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "State Payroll Taxes Payable",
		"accountNumber": 2360,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "SUTA Payable",
		"accountNumber": 2370,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Local Payroll Taxes Payable",
		"accountNumber": 2380,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Income Taxes Payable",
		"accountNumber": 2390,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Other Taxes Payable",
		"accountNumber": 2400,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Employee Benefits Payable",
		"accountNumber": 2410,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Current Portion of Long-term Debt",
		"accountNumber": 2420,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Deposits from Customers",
		"accountNumber": 2440,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Other Current Liabilities",
		"accountNumber": 2480,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Notes Payable",
		"accountNumber": 2700,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Land Payable",
		"accountNumber": 2702,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Equipment Payable",
		"accountNumber": 2704,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Vehicles Payable",
		"accountNumber": 2706,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Bank Loans Payable",
		"accountNumber": 2708,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Deferred Revenue",
		"accountNumber": 2710,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Other Long-term Liabilities",
		"accountNumber": 2740,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Opening Balance",
		"accountNumber": 3000,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Stated Capital",
		"accountNumber": 3010,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Capital Surplus",
		"accountNumber": 3020,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Retained Earnings",
		"accountNumber": 3030,
		"cashFlowCategory": "finance"
	},
	{
		"accountName": "Sales Income",
		"accountNumber": 4000,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Shipping and Handling Income",
		"accountNumber": 4050,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Interest Income",
		"accountNumber": 4060,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Other Income",
		"accountNumber": 4080,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Finance Charge Income",
		"accountNumber": 4540,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Shipping Charges Reimbursed",
		"accountNumber": 4550,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Sales Returns and Allowances",
		"accountNumber": 4800,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Sales Discounts",
		"accountNumber": 4900,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Cost of Goods Sold, Inventory",
		"accountNumber": 5000,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Raw Material Purchases",
		"accountNumber": 5050,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Direct Labor Costs",
		"accountNumber": 5100,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Indirect Labor Costs",
		"accountNumber": 5150,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Heat and Power",
		"accountNumber": 5200,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Commissions",
		"accountNumber": 5250,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Miscellaneous Factory Costs",
		"accountNumber": 5300,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Cost of Goods Sold, Salaries and Wages",
		"accountNumber": 5700,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Cost of Goods Sold, Contract Labor",
		"accountNumber": 5730,
		"cashFlowCategory": "operations"
	},
	{
		"accountName": "Cost of Goods Sold, Freight",
		"accountNumber": 5750,
		"cashFlowCategory": "operations"
	},
	{
